### ISSUE TITLE
Docs on how to use this

### ISSUE THREAD

**Issue by paibamboo** [crazyfactory/tinka#145]
Can't see it on readme

**Comment by cyberhck** [comment]
@paibamboo I wanted to have that long time ago, so I created a `documentation` branch.

There are a few examples, but that was when I think cache middleware wasn't merged, so I didn't create a PR, if you want, you can go through the changes and update it in such a way that a user can understand how to automatically generate SDK and use this client ALSO he'll understand how to use it standalone.

**Comment by paibamboo** [comment]
Where is the documentation branch?

**Comment by paibamboo** [comment]
In fact, I'm still not sure how to use it properly. The way we do it right now in tinka generator openapi is we have a class that extends Service and use `this.client.process`. That means when we actually use it, we need to create an instance all the time which I'm not sure about this.

```
export class ProductsNode extends Service {
  public productsList(options?: IFetchRequest): Promise<IProductsList> {
    return this.client.process({...{ url: `/products` }, ...options} as IFetchRequest);
  }
  public productsDetail(params: { id: number; search: string; }, options?: IFetchRequest): Promise<IProductsDetail> {
    return this.client.process({...{ url: `/products/${params.id}`, queryParameters: { search: params.search } }, ...options} as IFetchRequest);
  }
}
```

**Comment by cyberhck** [comment]
Right now we've a getter so we can do something like:
```TypeScript
// stored in DI and should be automatically injected or some other way to get the same instance.
const api = new ShopApi(new Client({base_url: "https://api.crazy-factory.com"}));
api.products.list().then((res) => {
  console.log(res)
})
```
That's when we generate API and use it. For stand alone, 
```TypeScript
const client = new Client({base_url: "https://api.crazy-factory.com"});
client.process({url: "/products/1", method: "GET"}).then((res) => {
  console.log(res);
});
```
Or what I'm doing in my other project is: I'm adding tinka as dependency, and I've a new class called HttpClient which looks like:
```TypeScript
export default HttpClient extends tinka.Client {
  public constructor(base_url: string);
  public get(url: string);
  public post(url: string, data: object); // I convert to string via a middleware
  public put(url: string, data: object);
  public delete(url: strinig);
  // add any helper method you'd like, return Tinka.Client.process
}
```
Then later in your code, you can do something along the lines of:
```TypeScript
// add to di and get from di later
const api = new HttpClient("https://api.crazy-factory.com");
api.get("/products/1").then();
api.post("/products", {...product_data}).then();
```

**Comment by cyberhck** [comment]
The last option on how to use it above, I was stupid, can't believe I did that, don't do that, simply create a sdk package and consume fully typed sdk, if you want to do simple fetch, I guess you can, but really? 🙁

**Comment by cyberhck** [comment]
I'll do some documentation soon (hopefully)
