### ISSUE TITLE
How to use cache middleware?

### ISSUE THREAD

**Issue by cyberhck** [crazyfactory/tinka#159]
Realizing we should have created proper docs for this repo.

What I want to know is when I add the cache middleware to tinka, how do I define which endpoints to cache and how long? After looking at tests, I think it is something like:
```typescript
const tinka = new Client({baseUrl: "https://api.example.com"});
tinka.addMiddleware(new CacheMiddleware(new RedisAdapter()))
tinka.process({url: "/me", cache: {enable: true, maxAge: 10}});
```

Is that correct? @adhocore or we just configure at first and same ttl is applied for all?

if not, how do set it up? and how do we define life for each endpoints?
Thanks in advance!

**Comment by adhocore** [comment]
aha been quite long. and most probably the code have been refactored by wolf since then. 

that snippet looks correct (at least as pseudo code if not at all)

**Comment by cyberhck** [comment]
wolf only did minor changes, AFAIK, okay, I needed to know a little more caching because I was about to create an issue related to caching soon :slightly_smiling_face: thanks.
/closing.
