### ISSUE TITLE
Should the repo name not be ts-fetch-client?

### ISSUE THREAD

**Issue by dacgray** [crazyfactory/tinka#51]
Just because.

**Comment by wmathes** [comment]
we can rename it at some point. 

The package-name is also still the old one, we will change that once we have reached a stable state. So the first release with the correct name can be a sentimental 1.0.0 :p

**Comment by wmathes** [comment]
Good chance we can actually do this next week :)

**Comment by wmathes** [comment]
"one week" later this has actually been done!
