### ISSUE TITLE
add a samples folder

### ISSUE THREAD

**Issue by wmathes** [crazyfactory/tinka#72]
*WE MAY DO THIS AS A SEPARATE PACKAGE INSTEAD*
aka tinka-samples

Add a simple sample to `/samples` which uses the actual generated umd file.

- [ ] dont publish (add to .npmignore).
- [ ] add /samples/raw/index.html similar to the current /umd/index.html to use as a playground.
- [ ] add /samples/jsonplaceholder/index.html with sample usage of jsonplaceholder.typicode.com api.

**Comment by cyberhck** [comment]
Samples folder
Pro: as a separate package, we can add documentation relative to version number, and update the required changes. Have to do once, and we'll not suddenly loose old version's documentation. Although, we do have git to look into history.
Con: Have to maintain as a separate package.

**Comment by cyberhck** [comment]
I'll just create a documentation with markdown, or in Wiki. And add a sample project which uses everything, from mock to fetch response.

**Comment by cyberhck** [comment]
now that we have docs, we'll close this.
